package com.moss.veracity.api.jaxws;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class AccountExistsResponse {

    private boolean Return;

    public boolean getReturn() {
        return Return;
    }

    public void setReturn(boolean Return) {
        this.Return = Return;
    }
}
