package com.moss.veracity.api.jaxws;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
@XmlRootElement
public class AccountExistsExceptionBean {

}
