package com.moss.veracity.api.jaxws;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class CreateResponse {

}
