package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtEndorsement;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class GetConfiguration {

    private VtEndorsement arg0;

    public VtEndorsement getArg0() {
        return arg0;
    }

    public void setArg0(VtEndorsement arg0) {
        this.arg0 = arg0;
    }
}
