package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtConfiguration;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class GetConfigurationResponse {

    private VtConfiguration Return;

    public VtConfiguration getReturn() {
        return Return;
    }

    public void setReturn(VtConfiguration Return) {
        this.Return = Return;
    }
}
