package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtProfile;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class GetProfileResponse {

    private VtProfile Return;

    public VtProfile getReturn() {
        return Return;
    }

    public void setReturn(VtProfile Return) {
        this.Return = Return;
    }
}
