package com.moss.veracity.api.jaxws;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class GetSignatureKey {

    private byte[] arg0;

    public byte[] getArg0() {
        return arg0;
    }

    public void setArg0(byte[] arg0) {
        this.arg0 = arg0;
    }
}
