package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtPublicSignatureKey;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class GetSignatureKeyResponse {

    private VtPublicSignatureKey Return;

    public VtPublicSignatureKey getReturn() {
        return Return;
    }

    public void setReturn(VtPublicSignatureKey Return) {
        this.Return = Return;
    }
}
