package com.moss.veracity.api.jaxws;

import java.lang.String;
import java.util.List;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class ListAccountNamesResponse {

    private List<String> Return;

    public List<String> getReturn() {
        return Return;
    }

    public void setReturn(List<String> Return) {
        this.Return = Return;
    }
}
