package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtEndorsement;
import java.lang.String;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class Read {

    private String arg0;

    private VtEndorsement arg1;

    public String getArg0() {
        return arg0;
    }

    public void setArg0(String arg0) {
        this.arg0 = arg0;
    }

    public VtEndorsement getArg1() {
        return arg1;
    }

    public void setArg1(VtEndorsement arg1) {
        this.arg1 = arg1;
    }
}
