package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtAccount;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class ReadResponse {

    private VtAccount Return;

    public VtAccount getReturn() {
        return Return;
    }

    public void setReturn(VtAccount Return) {
        this.Return = Return;
    }
}
