package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.XmlSeeAlso;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class Register {

    private XmlSeeAlso arg0;

    public XmlSeeAlso getArg0() {
        return arg0;
    }

    public void setArg0(XmlSeeAlso arg0) {
        this.arg0 = arg0;
    }
}
