package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtAccount;
import com.moss.veracity.api.VtEndorsement;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class Update {

    private VtAccount arg0;

    private VtEndorsement arg1;

    public VtAccount getArg0() {
        return arg0;
    }

    public void setArg0(VtAccount arg0) {
        this.arg0 = arg0;
    }

    public VtEndorsement getArg1() {
        return arg1;
    }

    public void setArg1(VtEndorsement arg1) {
        this.arg1 = arg1;
    }
}
