package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtToken;
import java.lang.String;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class Verify {

    private String arg0;

    private VtToken arg1;

    private String arg2;

    public String getArg0() {
        return arg0;
    }

    public void setArg0(String arg0) {
        this.arg0 = arg0;
    }

    public VtToken getArg1() {
        return arg1;
    }

    public void setArg1(VtToken arg1) {
        this.arg1 = arg1;
    }

    public String getArg2() {
        return arg2;
    }

    public void setArg2(String arg2) {
        this.arg2 = arg2;
    }
}
