package com.moss.veracity.api.jaxws;

import com.moss.veracity.api.VtEndorsement;

/**
 * WARNING: This file was dynamically generated by jaxws-stubgen! Any manual
 * changes made to this file will be overwritten.
 */
public class VerifyResponse {

    private VtEndorsement Return;

    public VtEndorsement getReturn() {
        return Return;
    }

    public void setReturn(VtEndorsement Return) {
        this.Return = Return;
    }
}
